name: Lint - example

on: [push]

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Node.js dependencies
        run: pnpm i --frozen-lockfile

      - name: Revert changes into the pnpm-lock.yaml file
        run: git checkout -- pnpm-lock.yaml

      - name: Run linters
        run: pnpm lint

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit lint fixes
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'feat: automated lint with biome'
          file_pattern: '.'
