name: Tests - example

on: [push]

jobs:
  test:
    name: Testing example
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Node.js dependencies
        run: pnpm i --frozen-lockfile

      - name: Revert changes into the pnpm-lock.yaml file
        run: git checkout -- pnpm-lock.yaml

      - name: Run test
        run: pnpm test:ci
